### ISSUE TITLE
Your VS Code extension is affected by a security issue and have been blocked

### ISSUE THREAD

**Issue by auchenberg** [r-koubou/vscode-ksp#7]
Hi,

Kenneth here from the VS Code team. 

Your extension is affected by https://code.visualstudio.com/blogs/2018/11/26/event-stream, and we have blocked your extension.

In order to enable your extension again the workflow is:
  
1) [ ] Fix the extension, submit an update to the marketplace
2) [ ] Send mail to VSMarketplace@microsoft.com and kennau@microsoft.com and notify us.
3) We will verify that the extension is okay
4) Our marketplace will publish the extension again and we'll remove the extension from the blocklist

/k

**Comment by r-koubou** [comment]
Hi,

We apologize for your inconvenience.

I just have fixed problem and submit an update to marketplace.
And send Email to you. Please verify my extension.

**Comment by r-koubou** [comment]
Published by VSCode team.

**Comment by r-koubou** [comment]
@auchenberg  Modified module "vscode" version 1.1.21 to 1.1.22 and extention version as 0.7.2 in package.json. And re-uploaded vsix. Now, Blocked again...
